# This file is auto-generated by scripts/generate_secrets.py
# It allows secrets to be compiled into the binary by Nuitka.

class Secrets:
    RAWG_API_KEY = "13437101070348cfb51b1f6f032a23ed"
    IGDB_CLIENT_ID = "your_id"
    IGDB_CLIENT_SECRET = "your_secret"
