import os
from pathlib import Path

def generate_secrets():
    root_dir = Path(__file__).parent.parent
    env_file = root_dir / ".env"
    output_file = root_dir / "engine" / "core" / "secrets_generated.py"

    print(f"Reading secrets from {env_file}...")
    
    if not env_file.exists():
        print(f"Warning: {env_file} not found. Skipping secret generation.")
        return

    secrets = {}
    with open(env_file, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, value = line.split("=", 1)
                secrets[key.strip()] = value.strip()

    print(f"Writing {len(secrets)} secrets to {output_file}...")
    
    with open(output_file, "w") as f:
        f.write("# This file is auto-generated by scripts/generate_secrets.py\n")
        f.write("# It allows secrets to be compiled into the binary by Nuitka.\n\n")
        f.write("class Secrets:\n")
        for key, value in secrets.items():
            # Basic escaping for string literal
            safe_value = value.replace('"', '\\"')
            f.write(f"    {key} = \"{safe_value}\"\n")

    print("Done.")

if __name__ == "__main__":
    generate_secrets()
